anchor: payment_config
owner: payment
stage: mvp
tags: [payment, config]
description: 多平台支付配置结构（Stripe, GooglePlay）
content:
  stripe:
    publishable_key: "env"
    webhook_secret: "env"
  google_play:
    service_account: "json_credential"
    package_name: "ai.facefusion"