product:
  description: '[AI补全] 示例 description 内容'
  example: '[AI补全] 示例 example 内容'
  implementation_hint: '[AI补全] 示例 implementation_hint 内容'
  positioning:
  - MVP主打Z世代情绪表达
  - 引导用户用“头像+模板”表达自我
  - 打造反差、幻想、叙事化体验
  tag: '[AI补全] 示例 tag 内容'
  value_proposition:
  - 社交传播性强，适合构建爆品话题
  - 提供低门槛情绪价值记录工具
  - 用户资产长期沉淀：形象、记忆、话题
