description: 记录当前使用的 Roop 模型调用参数、预处理与后处理设置。
fields:
  input_requirements:
    enhance_face: GFPGAN enabled
    face_alignment: 'True'
    resolution: 512x512
  model_version: 2024-roop-v2.3
  output_options:
    format: JPEG
    overlay_mask: false
    quality: 90
title: Roop 模型参数配置与调用约定
